version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MAX_CONTEXT_CHARS: 12000
      TOP_K_RETRIEVAL: 5
    volumes:
      - .:/app